context = Noizu.ElixirCore.CallingContext.admin()
{:ok, _} = Noizu.AdvancedPool.Test.Supervisor.start()
{:ok, _} = Noizu.AdvancedPool.Test.Supervisor.add_service(Noizu.AdvancedPool.Support.TestPool.pool_spec(context))
# GenServer.call(Noizu.AdvancedPool.Support.TestPool.Server, :Apple)
# Noizu.AdvancedPool.Message.Dispatch.s_call({:ref, Noizu.AdvancedPool.Support.TestPool.Server, 1234}, :hello, context)
ExUnit.start()